### ISSUE TITLE
Site 'apo' not in database

### ISSUE THREAD

**Issue by ViviCoder** [astropy/astroplan#416]
When running tests offline, I obtain the following error:
```
platform linux -- Python 3.7.4, pytest-3.10.1, py-1.8.0, pluggy-0.8.0

Running tests with astroplan version 0.5.
Running tests in astroplan docs.

Date: 2019-07-29T18:42:34

Platform: Linux-4.19.0-5-amd64-x86_64-with-debian-bullseye-sid

Executable: /usr/bin/python3.7

Full Python Version: 
3.7.4 (default, Jul 11 2019, 10:43:21) 
[GCC 8.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.16.2
Scipy: not available
Matplotlib: 3.0.2
Pandas: not available
Astropy: 3.2.1
pytz: 2019.1
pyephem: not available
matplotlib: 3.0.2
pytest-mpl: not available
astropy_helpers: 3.2.1
Using Astropy options: remote_data: none.

rootdir: /tmp/astroplan-test-jjfxab7s/lib/python3.7/site-packages, inifile: setup.cfg
plugins: remotedata-0.3.1, openfiles-0.4.0, doctestplus-0.3.0, arraydiff-0.3
collected 103 items / 2 errors

==================================== ERRORS ====================================
_____________ ERROR collecting astroplan/tests/test_scheduling.py ______________
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:350: in of_site
    el = registry[site_name]
/usr/lib/python3/dist-packages/astropy/coordinates/sites.py:58: in __getitem__
    raise UnknownSiteException(site_name, "the 'names' attribute", close_names=close_names)
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use the 'names' attribute to see available sites."

During handling of the above exception, another exception occurred:
astroplan/tests/test_scheduling.py:26: in <module>
    apo = Observer.at_site('apo')
astroplan/observer.py:258: in at_site
    return cls(location=EarthLocation.of_site(site_name), name=name, **kwargs)
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:352: in of_site
    raise UnknownSiteException(e.site, 'EarthLocation.get_site_names', close_names=e.close_names)
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use EarthLocation.get_site_names to see available sites."
_____________ ERROR collecting astroplan/tests/test_scheduling.py ______________
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:350: in of_site
    el = registry[site_name]
/usr/lib/python3/dist-packages/astropy/coordinates/sites.py:58: in __getitem__
    raise UnknownSiteException(site_name, "the 'names' attribute", close_names=close_names)
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use the 'names' attribute to see available sites."

During handling of the above exception, another exception occurred:
astroplan/tests/test_scheduling.py:26: in <module>
    apo = Observer.at_site('apo')
astroplan/observer.py:258: in at_site
    return cls(location=EarthLocation.of_site(site_name), name=name, **kwargs)
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:352: in of_site
    raise UnknownSiteException(e.site, 'EarthLocation.get_site_names', close_names=e.close_names)
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use EarthLocation.get_site_names to see available sites."
=============================== warnings summary ===============================
astroplan/plots/time_dependent.py:9
  /tmp/astroplan-test-jjfxab7s/lib/python3.7/site-packages/astroplan/plots/time_dependent.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Sequence

/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:537
  /usr/lib/python3/dist-packages/astropy/coordinates/earth.py:537: AstropyUserWarning: Could not access the online site list. Falling back on the built-in version, which is rather limited. If you want to retry the download, do EarthLocation._get_site_registry(force_download=True)
    warn(AstropyUserWarning(msg.format(cls.__name__)))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
```
This is probably due to the fact that the built-in database is used.

**Comment by olebole** [comment]
The [local database of astropy](https://github.com/astropy/astropy/blob/master/astropy/coordinates/data/sites.json) has only one entry (Greenwich), everything else is retrieved from [astropy-data](https://github.com/astropy/astropy-data). There are more that 50 calls of `Observer.at_site()` in the tests (APO, Subaru, LCO, Lapalma, KECK, KPNO, Greenwich).

For the moment, I would not see a way to run the astroplan tests without internet connection (f.e. in the Debian build infrastructure and in Debian CI), and probably it would be the best to disable it.

However, it would be nice if there would be a way -- either in astropy or in astroplan -- to provide a (small) set of observatories locally that can be used for tests. This however currently seems to lack a proper method in astropy -- I opened astropy/astropy#9213 for this.

Without tests that run locally, there would not be a reliable way in the Debian infrastructure to test the package.

**Comment by bmorris3** [comment]
This is due to an unfortunate update to astropy-helpers which accidentally overwrote some astroplan specific modifications to the testing infrastructure. Working on a fix in #438.

**Comment by ViviCoder** [comment]
@bmorris3 It seems that the refactoring of _astropy_init.py has reintroduced the bug:

```
============================= test session starts ==============================
platform linux -- Python 3.9.1+, pytest-6.0.2, py-1.10.0, pluggy-0.13.0

Running tests with astroplan version 0.8.
Running tests in astroplan docs.

Date: 2021-02-02T14:37:53

Platform: Linux-4.19.0-13-amd64-x86_64-with-glibc2.31

Executable: /usr/bin/python3.9

Full Python Version: 
3.9.1+ (default, Jan 20 2021, 14:49:22) 
[GCC 10.2.1 20210110]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.5
Scipy: not available
Matplotlib: 3.3.3
Pandas: not available
Astropy: 4.2
pytz: 2020.5
pyephem: not available
matplotlib: 3.3.3
pytest-mpl: not available

Using Astropy options: remote_data: none.

rootdir: /build/astroplan-0.8, configfile: setup.cfg, testpaths: astroplan, docs
plugins: openfiles-0.5.0, astropy-header-0.1.2, arraydiff-0.3, remotedata-0.3.2, doctestplus-0.9.0, filter-subpackage-0.1.1, cov-2.10.1, hypothesis-5.43.3
collected 85 items / 2 errors / 83 selected

==================================== ERRORS ====================================
_____________ ERROR collecting astroplan/tests/test_scheduling.py ______________
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:361: in of_site
    el = registry[site_name]
/usr/lib/python3/dist-packages/astropy/coordinates/sites.py:58: in __getitem__
    raise UnknownSiteException(site_name, "the 'names' attribute", close_names=close_names)
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use the 'names' attribute to see available sites."

During handling of the above exception, another exception occurred:
astroplan/tests/test_scheduling.py:26: in <module>
    apo = Observer(EarthLocation.of_site('apo'), name='APO')
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:363: in of_site
    raise UnknownSiteException(e.site, 'EarthLocation.get_site_names',
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use EarthLocation.get_site_names to see available sites."
_____________ ERROR collecting astroplan/tests/test_scheduling.py ______________
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:361: in of_site
    el = registry[site_name]
/usr/lib/python3/dist-packages/astropy/coordinates/sites.py:58: in __getitem__
    raise UnknownSiteException(site_name, "the 'names' attribute", close_names=close_names)
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use the 'names' attribute to see available sites."

During handling of the above exception, another exception occurred:
astroplan/tests/test_scheduling.py:26: in <module>
    apo = Observer(EarthLocation.of_site('apo'), name='APO')
/usr/lib/python3/dist-packages/astropy/coordinates/earth.py:363: in of_site
    raise UnknownSiteException(e.site, 'EarthLocation.get_site_names',
E   astropy.coordinates.errors.UnknownSiteException: "Site 'apo' not in database. Use EarthLocation.get_site_names to see available sites."
```

As a workaround, I added back the lines
```
from .utils import _mock_remote_data
_mock_remote_data()
```

**Comment by bmorris3** [comment]
Hey @mwcraig, does this error make sense to you from an astropy perspective? I'm surprised this error occurs at all.

**Comment by mwcraig** [comment]
@bmorris3 -- That was my bad here: https://github.com/astropy/astroplan/commit/08b9be56608ad06913463ac8b40cbdd832700794#diff-69217915b5c1646adad435a94fbdf09722e5993691c6ff2d34d46d83058d016eL109

I missed those lines completely in making the transition. 

@ViviCoder -- do you want to open a PR to fix this or would you like one of us to fix it?

**Comment by bmorris3** [comment]
Thanks so much for tracking that down!

**Comment by ViviCoder** [comment]
@mwcraig I can open a PR, but I do not know how to test if remote_data is enabled, as done previously.

**Comment by sergiopasra** [comment]
While a better solution is developed, why not use fixed coordinates for "apo"?

```
apo = Observer(EarthLocation(-1463969.30185172, -5166673.34223433, 3434985.71204565, unit='m'), name='APO')
```

**Comment by ViviCoder** [comment]
I tried to patch it. Collection succeeds, but then there are a lot of test failures.
APO is used in several other places.
Other locations are also needed for tests: Subaru, LCO, and lapalma, several times each.
There are also failures because of targets (Sirius, A Polaris). This is probably related to the same database issue.

**Comment by bmorris3** [comment]
Closing as I believe this is fixed. Please reopen if necessary.

**Comment by ViviCoder** [comment]
@bmorris3 The issue is not fixed. I still get the same errors.

**Comment by sergiopasra** [comment]
Yes, the tests don't run in Fedora infrastructure. Everything that requires internet access fails. How do we reopen the issue?
